### ISSUE TITLE
after update, I see container images twice ...

### ISSUE THREAD

**Issue by pakair** [geerlingguy/internet-monitoring#11]
I updated containers with "docker pull containerID" but now "docker images" lists repositories twice (see below).

Q. How do I get rid of the old (4 weeks) and keep the latest? In general,
how do I keep my system up-to-date with changes fixed on the github repo?

Thanks, Paul

```
REPOSITORY                             TAG       IMAGE ID       CREATED          SIZE
prom/blackbox-exporter                 latest    c9e462ce1ee4   56 minutes ago   20.9MB
miguelndecarvalho/speedtest-exporter   latest    753d258c0c79   7 days ago       62.6MB
miguelndecarvalho/speedtest-exporter   <none>    d33228cf0959   4 weeks ago      62MB
grafana/grafana                        latest    13b20b4fe691   4 weeks ago      204MB
prom/prometheus                        latest    6d6859d1a42a   5 weeks ago      169MB
prom/prometheus                        v2.25.2   9ef343b5ed33   7 weeks ago      175MB
prom/node-exporter                     latest    c19ae228f069   2 months ago     26MB
prom/blackbox-exporter                 <none>    fd1563338c71   7 months ago     20.9MB
```

**Comment by geerlingguy** [comment]
The question of keeping things up to date is a little more complicated, so I'll hold off on that, but to clean up images that are no longer in use, you can use `docker system prune --all`, and it will remove any images or containers not currently running.

**Comment by geerlingguy** [comment]
See also: https://github.com/geerlingguy/internet-pi/issues/7
