### ISSUE TITLE
Prometheus pinghosts.yaml changes not reflected by grafana

### ISSUE THREAD

**Issue by Sathorn** [geerlingguy/internet-monitoring#13]
I changed targets for ping tests, and it is not reflected by Grafana. There is still three default targets: github, google and jeefgerling.com.

Of course I did 
docker-compose up -d 
but there was no change reflected like it was when I change password in grafana files.
Here is my config:
'- targets:  # url;humanname;routing;switch
        - http://91.214.0.129;Timplus1;external;US8
        - http://91.214.0.98;Timplus2;external;US8
        - http://www.onet.pl;Onet;external;US8
    # - http://www.google.com/;google.com;external;internetbox
    # - https://github.com/;github.com;external;internetbox
    # - https://www.jeffgeerling.com;jeffgeerling.com;external;internetbox
    # - http://192.168.1.1;internetbox;local;internetbox
    # - http://192.168.1.42;blackdata;local;orbirouter-attic
    # - http://192.168.1.101;orbirouter;local;orbirouter
'

**Comment by geerlingguy** [comment]
You may need to restart the containers to pick up the change, ideally with `docker-compose restart`.

**Comment by geerlingguy** [comment]
I'll be archiving this repository as the contents have been merged into my [internet-pi](https://github.com/geerlingguy/internet-pi) repository—please feel free to re-open this issue in that repo to keep the conversation going!

More details: https://github.com/geerlingguy/internet-monitoring/issues/22
