### ISSUE TITLE
SMTP Setup on Docker Install

### ISSUE THREAD

**Issue by ArtMason** [geerlingguy/internet-monitoring#2]
Hello!

I have been going through the docs to try to figure out how I can setup smtp on a docker install. I am monitoring my websites and server but would like email alters for any downtime.  I am also using the Mailgun service.

Any help or direction would be appreciated.

Thank you!

Art

**Comment by georgettica** [comment]
@ArtMason it seems this is not exactly baked in prometheus, but it's in alertmanager which integrates with prometheus nicely

see https://prometheus.io/docs/alerting/latest/configuration/ for smtp configs
also, this would be an additional container you will be required to run on your machine to do this work

**Comment by geerlingguy** [comment]
This is also something you'd be able to configure through Grafana; see https://grafana.com/docs/grafana/latest/alerting/

**Comment by geerlingguy** [comment]
For now, it's out of scope for this project though, because I'm just doing monitoring, not alerting as well (that can open a whole new can of worms).
