### ISSUE TITLE
[feature] measure web "experience" time

### ISSUE THREAD

**Issue by cfuentea** [geerlingguy/internet-monitoring#20]
hello everyone! have you ever tried to use selenium to measure the times that takes to websites to load (i mean from the initial HTTP response to the full page loaded)?

**Comment by geerlingguy** [comment]
I have before, though especially if done frequently, this would consume a lot more bandwidth than the simple http 200 OK checks currently performed, plus this tool is more meant to test a general internet connection, and less as a tool to test various websites frontend load performance.

And while a general experience test can help with that, unless there's a simple way to support that without consuming a lot more bandwidth I'd rather not add it at this time.
