### ISSUE TITLE
Speedtest container keeps restarting

### ISSUE THREAD

**Issue by jordanarpad** [geerlingguy/internet-monitoring#21]
I have a 2 GB Raspberry Pi running 32-bit PiOS that I otherwise use as an ADS-B receiver. I installed this repo on it, but the speedtest container keeps restarting. This is what I see added in the container log every minute:
Current thread 0xb6f76390 (most recent call first):
<no Python frame>
Fatal Python error: init_interp_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

What could be wrong?

**Comment by mikecannondeveloper** [comment]
I am also experiencing this same issue

**Comment by mikecannondeveloper** [comment]
Running these commands on the pi fixed it for me: 
`
wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb
`

**Comment by jordanarpad** [comment]
thank you - this made the trick for me also!
