### ISSUE TITLE
Speedtest-Exporter always Unhealthy Status

### ISSUE THREAD

**Issue by xtreme2020** [geerlingguy/internet-monitoring#4]
Logs show 
[2021-04-15 14:16:46.303] [error] Configuration - Cannot retrieve configuration document (0)
,[2021-04-15 14:16:46.304] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
,[2021-04-15 14:16:46.304] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
,{
,    "type": "log",
,    "timestamp": "2021-04-15T14:16:46Z",
,    "message": "Configuration - Could not retrieve or read configuration (ConfigurationError)",
,    "level": "error"
,}
,ERROR:Speedtest-Exporter:Exception on /metrics [GET]
,Traceback (most recent call last):
,  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
,    response = self.full_dispatch_request()
,  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
,    rv = self.handle_user_exception(e)
,  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
,    reraise(exc_type, exc_value, tb)
,  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
,    raise value
,  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
,    rv = self.dispatch_request()
,  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
,    return self.view_functions[rule.endpoint](**req.view_args)
,  File "/app/exporter.py", line 70, in updateResults
,    r_server, r_jitter, r_ping, r_download, r_upload, r_status = runTest()
,  File "/app/exporter.py", line 47, in runTest
,    output = subprocess.check_output(cmd)
,  File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
,    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
,  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
,    raise CalledProcessError(retcode, process.args,
,subprocess.CalledProcessError: Command '['speedtest', '--format=json-pretty', '--progress=no', '--accept-license', '--accept-gdpr']' returned non-zero exit status 2.
,[2021-04-15 14:38:22.019] [error] Trying to get interface information on non-initialized socket.
,[2021-04-15 14:38:27.535] [error] Configuration - Couldn't resolve host name (HostNotFoundException)
,[2021-04-15 14:38:27.535] [error] Configuration - Cannot retrieve configuration document (0)
,[2021-04-15 14:38:27.536] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
,[2021-04-15 14:38:27.536] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
,{
,    "type": "log",
,    "timestamp": "2021-04-15T14:38:27Z",
,    "message": "Configuration - Could not retrieve or read configuration (ConfigurationError)",
,    "level": "error"
,}
,ERROR:Speedtest-Exporter:Exception on /metrics [GET]
,Traceback (most recent call last):
,  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
,    response = self.full_dispatch_request()
,  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
,    rv = self.handle_user_exception(e)
,  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
,    reraise(exc_type, exc_value, tb)
,  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
,    raise value
,  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
,    rv = self.dispatch_request()
,  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
,    return self.view_functions[rule.endpoint](**req.view_args)
,  File "/app/exporter.py", line 70, in updateResults
,    r_server, r_jitter, r_ping, r_download, r_upload, r_status = runTest()
,  File "/app/exporter.py", line 47, in runTest
,    output = subprocess.check_output(cmd)
,  File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
,    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
,  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
,    raise CalledProcessError(retcode, process.args,
,subprocess.CalledProcessError: Command '['speedtest', '--format=json-pretty', '--progress=no', '--accept-license', '--accept-gdpr']' returned non-zero exit status 2.
,[2021-04-15 16:28:01.854] [error] Trying to get interface information on non-initialized socket.
,[2021-04-15 16:28:07.373] [error] Configuration - Couldn't resolve host name (HostNotFoundException)
,[2021-04-15 16:28:07.373] [error] Configuration - Cannot retrieve configuration document (0)
,[2021-04-15 16:28:07.374] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
,[2021-04-15 16:28:07.374] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
,{
,    "type": "log",
,    "timestamp": "2021-04-15T16:28:07Z",
,    "message": "Configuration - Could not retrieve or read configuration (ConfigurationError)",
,    "level": "error"
,}
,ERROR:Speedtest-Exporter:Exception on /metrics [GET]
,Traceback (most recent call last):
,  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
,    response = self.full_dispatch_request()
,  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
,    rv = self.handle_user_exception(e)
,  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
,    reraise(exc_type, exc_value, tb)
,  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
,    raise value
,  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
,    rv = self.dispatch_request()
,  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
,    return self.view_functions[rule.endpoint](**req.view_args)
,  File "/app/exporter.py", line 70, in updateResults
,    r_server, r_jitter, r_ping, r_download, r_upload, r_status = runTest()
,  File "/app/exporter.py", line 47, in runTest
,    output = subprocess.check_output(cmd)
,  File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
,    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
,  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
,    raise CalledProcessError(retcode, process.args,
,subprocess.CalledProcessError: Command '['speedtest', '--format=json-pretty', '--progress=no', '--accept-license', '--accept-gdpr']' returned non-zero exit status 2.
,

**Comment by MiguelNdeCarvalho** [comment]
Hey,

@xtreme2020 is it possible for you to create an issue [here](https://github.com/MiguelNdeCarvalho/speedtest-exporter/issues) please?

Thanks,
MiguelNdeCarvalho

**Comment by xtreme2020** [comment]
> Hey,
> 
> 
> 
> @xtreme2020 is it possible for you to create an issue [here](https://github.com/MiguelNdeCarvalho/speedtest-exporter/issues) please?
> 
> 
> 
> Thanks,
> 
> MiguelNdeCarvalho 

Ok, thanks, i will.

**Comment by xtreme2020** [comment]
Hi, everyone already got it working, for some reason there was a problem with the network assigned by docker, so I started the container with docker run -d --network host --name speedtest-exporter miguelndecarvalho/speedtest-exporter:v3.1 , once I changed the network to host everything start working
