### ISSUE TITLE
Add Starlink monitoring

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/internet-monitoring#6]
Through my internet-pi project, I'd like to add in Starlink monitoring using https://github.com/danopstech/starlink_exporter (though I've run into one issue here: https://github.com/danopstech/starlink_exporter/issues/1

**Comment by geerlingguy** [comment]
See also @dwillcocks' dashboard here for reference: https://github.com/danopstech/starlink/blob/main/config/grafana/provisioning/dashboards/boards/starlink_overview.json

**Comment by geerlingguy** [comment]
Hehe, got the dashboard up but it's having a little trouble getting data (even though Prometheus is saying the target's healthy...):

<img width="1181" alt="Screen Shot 2021-04-27 at 12 55 44 PM" src="https://user-images.githubusercontent.com/481677/116289257-f63b3200-a757-11eb-8626-d29a8cf6fb06.png">

**Comment by geerlingguy** [comment]
It's strange, because when I use the query inspector and jump to Prometheus, the query shows up just fine...

<img width="1254" alt="Screen Shot 2021-04-27 at 1 03 20 PM" src="https://user-images.githubusercontent.com/481677/116290323-f5ef6680-a758-11eb-8f6f-9da18aa4674b.png">

**Comment by geerlingguy** [comment]
There we go; disabled all `exemplars` and was able to get data. Honestly I don't know much about how that feature works...

<img width="1254" alt="Screen Shot 2021-04-27 at 1 08 08 PM" src="https://user-images.githubusercontent.com/481677/116290962-a9f0f180-a759-11eb-90ec-810811a11845.png">

**Comment by geerlingguy** [comment]
Man, this is nice... love all the detail that went into this dashboard, replicating everything in the app and then some!

<img width="649" alt="Screen Shot 2021-04-27 at 1 13 23 PM" src="https://user-images.githubusercontent.com/481677/116291605-6480f400-a75a-11eb-9992-6bbf9f90f755.png">

**Comment by geerlingguy** [comment]
Before wrapping up, I need to fix two graphs:

  - [ ] Speed Test (the little metric)
  - [ ] 3x under 'Best Speedtest.net In Last 24 Hours

I need to get those wired up to the metrics coming from the speedtest exporter I already have running.

**Comment by dwillcocks** [comment]
> I need to get those wired up to the metrics coming from the speedtest exporter I already have running.

Depends what else you have hooked up (metric names will definitely be different). and your need to update the dashboard json again (I fixed it last night) then.... https://github.com/danopstech/speedtest_exporter
