### ISSUE TITLE
Uptime graph hides outages when zoomed out over longer periods

### ISSUE THREAD

**Issue by Conor-Burns** [geerlingguy/internet-monitoring#8]
Hi,

Is it possible to mark a square in the statusmap red when downtime occurred and also keep it red in larger timespans?
![](https://s.0xcb.dev/ootgU)
![](https://s.0xcb.dev/BWNKt)
Like if one minute is red also make the day red?

**Comment by geerlingguy** [comment]
@Conor-Burns - I've actually been messing with that a bit. I can't figure out a way to make it so if there's any red within a range, it shows the block as red when aggregated. So it does mask out brief outages quite a bit over longer periods.

I have considered opening an issue on the plugin (grafana-tatusmap) issue queue: https://github.com/flant/grafana-statusmap

Another option would be to try to figure out if there's a way to rebuild this with heatmap, but not sure...

**Comment by Conor-Burns** [comment]
would definitely be really nice, thank you for your time!

**Comment by geerlingguy** [comment]
See related: https://github.com/geerlingguy/internet-monitoring/issues/14 — the new State timeline graph type might do a better job... just need to upgrade and test it out.

**Comment by geerlingguy** [comment]
I'll be archiving this repository as the contents have been merged into my [internet-pi](https://github.com/geerlingguy/internet-pi) repository—please feel free to re-open this issue in that repo to keep the conversation going!

More details: https://github.com/geerlingguy/internet-monitoring/issues/22
