### ISSUE TITLE
Speedtest-Exporter container healthy, but data not showing in Grafana

### ISSUE THREAD

**Issue by ilyesm** [geerlingguy/internet-monitoring#9]
Hi there,

I am not sure if I may be doing something wrong, but the speedtest-exporter container is healthy and up, but on the Grafana dashboards on :3030, I am only occasionally seeing speedtest data.

![image](https://user-images.githubusercontent.com/22662322/117547026-5322cc00-b025-11eb-8b35-fd45db71ecf9.png)

![image](https://user-images.githubusercontent.com/22662322/117547038-63d34200-b025-11eb-892c-1ae9cc465ef8.png)

Any clues as to what may be happening?

Thanks.
ilyesm

**Comment by pakair** [comment]
I see your containers just started 33 min ago. maybe you need to wait a few hours to collect data. I have "Last 24 hours" for the time range.

**Comment by ilyesm** [comment]
Thanks @pakair. Might have identified the reason, the scrape_interval is set to 30m. Will change to 15m and see if this gives me more frequent speedtest results, and will close if that's the case.

**Comment by ilyesm** [comment]
Hi there. Seems like this was a non-issue, and was being caused by the scrape_interval. Closing this issue. Thanks.

**Comment by geerlingguy** [comment]
@ilyesm - Yeah; I set it to 30m just to be a little more on the safe side, in case someone has data caps and I don't want the default setting to blow through those right away (I initially had it do a speedtest every 5m!).
